[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "trainfinity2"
description = ''
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
authors = [
  { name = "Filip Lange", email = "filip.lange@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
dependencies = []
dynamic = ["version"]

[project.urls]
Documentation = "https://github.com/Godsmith/trainfinity2#readme"
Issues = "https://github.com/Godsmith/trainfinity2/issues"
Source = "https://github.com/Godsmith/trainfinity2"

[tool.hatch.version]
path = "trainfinity2/__about__.py"

[tool.hatch.envs.default]
dependencies = [
"arcade==2.6.15",
"black==22.6.0",
"pytest==7.1.2",
"pytest-cov==3.0.0",
"perlin_noise==1.12",
"more-itertools==9.1.0",
"mypy==1.5.1",
"pre-commit==3.3.3",
]
[tool.hatch.envs.default.scripts]
start = "python -m trainfinity2"
cov = "python -m pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=trainfinity2 --cov=tests"
no-cov = "cov --no-cov"

[[tool.hatch.envs.test.matrix]]
python = ["310", "311"]

[tool.coverage.run]
branch = true
parallel = true
omit = [
  "trainfinity2/__about__.py",
]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.ruff]
ignore = ["E501"]

[tool.mypy]
mypy_path = "$MYPY_CONFIG_FILE_DIR/stubs"
check_untyped_defs = true
